SELECT tp.id, lp.nombre AS linea_producto,tp.linea_producto_id, tp.nombre, tp.activo 
FROM dbo.tipos_productos AS tp
INNER JOIN dbo.lineas_productos AS lp
ON lp.id = tp.linea_producto_id


SELECT p.id, tp.nombre AS tipo_producto, p.tipo_producto_id, p.nombre, p.activo 
FROM dbo.productos AS p
INNER JOIN dbo.tipos_productos AS tp
ON tp.id = p.tipo_producto_id

SELECT r.id, s.nombre AS sucursal,r.sucursal_id, r.nombre, r.activo 
FROM dbo.rutas AS r
INNER JOIN dbo.sucursales AS s
ON s.id = r.sucursal_id

select GETDATE()

SELECT e.persona_id,pu.nombre AS puesto, p.nombre, p. ap_paterno, p.ap_materno, 
p.fecha_nacimiento, p.sexo,ec.nombre AS estado_civil,p.estado_civil_id,e.puesto_id, e.fecha_registro, e.activo 
FROM dbo.empleados AS e
INNER JOIN dbo.personas AS p ON p.id = e.persona_id
INNER JOIN dbo.estados_civiles AS ec ON ec.id = p.estado_civil_id
INNER JOIN dbo.puestos AS pu ON pu.id = e.puesto_id


select * from personas

select * from clientes

select * from empleados


SELECT 
c.persona_id, o.nombre AS ocupacion, ti.nombre AS tipo_identificacion,p.nombre, p. ap_paterno, p.ap_materno, 
p.fecha_nacimiento, p.sexo, ec.nombre AS estado_civil,p.estado_civil_id,c.ocupacion_id, c.tipo_identificacion_id, c.fecha_registro, c.activo 
FROM dbo.clientes AS c
INNER JOIN dbo.personas AS p ON p.id = c.persona_id
INNER JOIN dbo.estados_civiles AS ec ON ec.id = p.estado_civil_id
INNER JOIN dbo.ocupaciones AS o ON o.id = c.ocupacion_id
INNER JOIN dbo.tipos_identificacion AS ti ON ti.id = c.tipo_identificacion_id

UPDATE personas SET estado_civil_id = 1
--INSERT INTO estados_civiles VALUES(1,'Soltero',1)
--INSERT INTO estados_civiles VALUES(2,'Casado',1)
--INSERT INTO estados_civiles VALUES(3,'Divorciado',1)
--INSERT INTO estados_civiles VALUES(4,'Viudo',1)

SELECT m.id, tmc.nombre AS medio_comunicacion, m.valor, (p.nombre + ' '+ p.ap_paterno+ ' ' +p.ap_materno) AS nombre_completo,m.tipo_medio_comunicacion_id, m.persona_id, m.activo
FROM medios_comunicacion AS m
INNER JOIN dbo.tipos_medios_comunicacion AS tmc ON tmc.id = m.tipo_medio_comunicacion_id
INNER JOIN dbo.personas AS p ON p.id = m.persona_id
--WHERE        (m.persona_id = @persona_id)
WHERE        (m.persona_id = 7)


 
select * from PERSONAS

INSERT INTO estados VALUES(1,'Aguascalientes',1)
INSERT INTO estados VALUES(2,'Baja California',1)
INSERT INTO estados VALUES(3,'Baja California Sur',1)
INSERT INTO estados VALUES(4,'Campeche',1)
INSERT INTO estados VALUES(5,'Chiapas',1)
INSERT INTO estados VALUES(6,'Chihuahua',1)
INSERT INTO estados VALUES(7,'Ciudad de México',1)
INSERT INTO estados VALUES(8,'Coahuila de Zaragoza',1)
INSERT INTO estados VALUES(9,'Colima',1)
INSERT INTO estados VALUES(10,'Durango',1)
INSERT INTO estados VALUES(11,'Guanajuato',1)
INSERT INTO estados VALUES(12,'Guerrero',1)
INSERT INTO estados VALUES(13,'Hidalgo',1)
INSERT INTO estados VALUES(14,'Jalisco',1)
INSERT INTO estados VALUES(15,'México',1)
INSERT INTO estados VALUES(16,'Michoacán de Ocampo',1)
INSERT INTO estados VALUES(17,'Morelos',1)
INSERT INTO estados VALUES(18,'Nayarit',1)
INSERT INTO estados VALUES(19,'Nuevo León',1)
INSERT INTO estados VALUES(20,'Oaxaca',1)
INSERT INTO estados VALUES(21,'Puebla',1)
INSERT INTO estados VALUES(22,'Querétaro de Arteaga',1)
INSERT INTO estados VALUES(23,'Quintana Roo',1)
INSERT INTO estados VALUES(24,'San Luis Potosí',1)
INSERT INTO estados VALUES(25,'Sinaloa',1)
INSERT INTO estados VALUES(26,'Sonora',1)
INSERT INTO estados VALUES(27,'Tabasco',1)
INSERT INTO estados VALUES(28,'Tamaulipas',1)
INSERT INTO estados VALUES(29,'Tlaxcala',1)
INSERT INTO estados VALUES(30,'Veracruz de Ignacio de la Llave',1)
INSERT INTO estados VALUES(31,'Yucatán',1)
INSERT INTO estados VALUES(32,'Zacatecas',1)

INSERT INTO municipios VALUES(1,27,'Balancán',1)
INSERT INTO municipios VALUES(2,27,'Cárdenas',1)
INSERT INTO municipios VALUES(3,27,'Centla',1)
INSERT INTO municipios VALUES(4,27,'Centro',1)
INSERT INTO municipios VALUES(5,27,'Comalcalco',1)
INSERT INTO municipios VALUES(6,27,'Cunduacán',1)
INSERT INTO municipios VALUES(7,27,'Emiliano Zapata',1)
INSERT INTO municipios VALUES(8,27,'Huimanguillo',1)
INSERT INTO municipios VALUES(9,27,'Jalapa',1)
INSERT INTO municipios VALUES(10,27,'Jalpa de Méndez',1)
INSERT INTO municipios VALUES(11,27,'Jonuta',1)
INSERT INTO municipios VALUES(12,27,'Macuspana',1)
INSERT INTO municipios VALUES(13,27,'Nacajuca',1)
INSERT INTO municipios VALUES(14,27,'Paraíso',1)
INSERT INTO municipios VALUES(15,27,'Tacotalpa',1)
INSERT INTO municipios VALUES(16,27,'Teapa',1)
INSERT INTO municipios VALUES(17,27,'Tenosique',1)

INSERT INTO tipos_asentamientos VALUES(1,'Ranchería',1)
INSERT INTO tipos_asentamientos VALUES(2,'Colonia',1)
INSERT INTO tipos_asentamientos VALUES(3,'Poblado comunal',1)
INSERT INTO tipos_asentamientos VALUES(4,'Ejido',1)
INSERT INTO tipos_asentamientos VALUES(5,'Barrio',1)
INSERT INTO tipos_asentamientos VALUES(6,'Congregación',1)
INSERT INTO tipos_asentamientos VALUES(7,'Villa',1)
INSERT INTO tipos_asentamientos VALUES(8,'Equipamiento',1)
INSERT INTO tipos_asentamientos VALUES(9,'Ingenio',1)
INSERT INTO tipos_asentamientos VALUES(10,'Pueblo',1)
INSERT INTO tipos_asentamientos VALUES(11,'Ampliación',1)
INSERT INTO tipos_asentamientos VALUES(12,'Fraccionamiento',1)
INSERT INTO tipos_asentamientos VALUES(13,'Campamento',1)
INSERT INTO tipos_asentamientos VALUES(14,'Unidad habitacional',1)
INSERT INTO tipos_asentamientos VALUES(15,'Gran usuario',1)
INSERT INTO tipos_asentamientos VALUES(16,'Zona industrial',1)
INSERT INTO tipos_asentamientos VALUES(17,'Residencial',1)
INSERT INTO tipos_asentamientos VALUES(18,'Aeropuerto',1)
INSERT INTO tipos_asentamientos VALUES(19,'Conjunto habitacional',1)
INSERT INTO tipos_asentamientos VALUES(20,'Condominio',1)

INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(15,4,'Teléfonos de México S.A. de CV',86006,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'El Recreo',86020,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Jose Maria Pino Suárez',86029,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Tierra Colorada',86029,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Heriberto Kehoe Vicent',86030,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Carrizal',86038,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Sol Campestre',86039,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Lidia Esther Mónica de Portilla',86040,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(18,4,'Villahermosa (Cap. P. A. Carlos Rovirosa)',86049,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Jose N Rovirosa',86050,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Loma Linda',86050,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Centro Delegacional 3',86077,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Centro Delegacional 4',86077,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Atasta',86100,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'España',86107,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Hacienda Buena Vista',86126,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Joyas de Buena Vista',86126,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Manuel Andrade Díaz',86126,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Miguel Hidalgo 2a Sección',86127,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Vista Alegre',86137,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'18 de Marzo',86140,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(17,4,'Los Robles',86143,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'El Edén',86153,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Edén Premier',86153,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(14,4,'Fovissste 2a Etapa',86170,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Plaza Jardín',86170,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Bugambilias',86180,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(17,4,'Deportiva Residencial',86189,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Parrilla 1a Sección',86195,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(10,4,'La Manga',86255,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'3er. Milenio',86256,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(7,4,'Ocuiltzapotlan',86270,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Isset',86270,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Kilómetro 15 Induvitab',86270,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Los Angeles',86270,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Real de Diamante',86270,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(10,4,'La Vuelta (laguna)',86274,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(10,4,'2 Montes',86275,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Medellín y Pigua 4a Secc (El Aguacate)',86276,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(17,4,'La Huerta',86276,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Las Giraldas',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Alfa y Omega',86281,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Casas Para Todos',86284,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(7,4,'Parrilla',86284,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Unión Hace La Fuerza',86284,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(10,4,'Gaviotas Sur 2a Sección',86284,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'El Árbol 1ra',86284,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Corregidora Ortiz 2a Secc',86287,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(10,4,'Anacleto Canabal 3a Sección',86287,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Villa los Claustros',86288,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Santa Bárbara',86288,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'La Venta',86288,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'27 de Octubre',86288,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Alvarado (Colima)',86291,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(4,4,'Subteniente Garcia',86291,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Alvarado Jimbal 3a Secc',86292,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Estanzuela 1a Secc',86293,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Pablo L. Sidar (Guineo)',86295,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Coronel Traconis 2a (El Zapote)',86296,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(15,4,'Palacio de Gobierno Del Estado de Tabasco',86009,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Ciudad Industrial',86010,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Cosmos',86017,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Lagunas',86019,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Olmeca',86019,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Villa de las Palmas',86026,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Jardines de Villahermosa',86027,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Paseos Del Usumacinta',86035,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Galaxia',86035,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Club de Lago',86035,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'La Gran Villa',86035,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Las Torres',86039,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(17,4,'Puerta de Hierro',86039,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Gaviotas Norte Sector Popular',86067,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Centro Delegacional 1',86077,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Reforma',86080,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(15,4,'DIR Gral. de Servicios Coordinados de Educación Publica',86086,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Villa de los Trabajadores',86108,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'El Espejo 2',86109,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Guadalupe Borja',86120,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Islas Del Mundo',86126,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Santa Elena',86126,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Villa las Torres',86126,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Edificio Del Rio Viejo',86127,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Macuili',86127,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Proclama',86127,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Ixtacomitán 1ra. Sección',86143,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'San Jorge III',86153,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'San José',86153,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(14,4,'Fovissste 1a Etapa',86180,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Primero de Mayo',86190,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Parrilla II',86193,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Jolochero (Boca de Culebra)',86250,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(10,4,'La Estancia Vieja',86253,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Aztlán 5ta. Sección (Palomillal)',86255,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Lomas Del Encanto',86270,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Tierra Amarilla 1a Secc',86272,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(10,4,'El Novillo',86273,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'La Palma',86275,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(10,4,'Boca de Guanal',86276,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Acachapan y Colmena 7a Sección (el Agricultor)',86277,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(10,4,'Boca de Aztlán',86278,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Agraria',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Gonzalez 3a Secc',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Lázaro Cárdenas 1a Sección',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Rio Viejo 4a Secc',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Las Hadas',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Américas',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Los Mezquites',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Rio Tinto 1a Secc',86283,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Fovissste Kilómetro 9',86284,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Popular Manuel Silva',86284,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(10,4,'Anacleto Canabal 4a Sección',86287,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Puerta Grande',86287,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'El Almendro',86288,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(7,4,'Pueblo Nuevo de las Raíces',86289,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Tumbuluschal',86290,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Boquerón 2a Sección (El Barquillo)',86293,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Torno Largo 2a Secc',86293,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Bosques de Araba',86294,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Miraflores 1a (Arroyo Grande)',86297,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(15,4,'Secretaria de La Reforma Agraria',86008,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(14,4,'Infonavit',86018,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Laguna de Mecoacan',86019,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Los Ríos',86035,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Club Campestre',86037,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Parque Tabasco',86037,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Magisterial',86040,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(15,4,'Secretaria de La Defensa Nacional',86087,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(15,4,'Procuraduría General de Justicia',86088,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Militar',86107,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Rio Viejo 3a Sección',86127,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Miguel Hidalgo 1a Sección',86127,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(17,4,'Olimpo',86127,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Miguel Hidalgo',86128,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(14,4,'Artesanos Infonavit',86130,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Miguel Hidalgo 5a Sección',86143,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Plaza Villahermosa',86179,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Marcos Buendia',86190,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'La Providencia (La Majahua)',86193,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(7,4,'Villa Unión',86250,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Alambrada',86250,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Reforma',86250,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Lomas de Ocuiltzapotlan',86270,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Tierra Amarilla 2a Sección (El Amatón)',86270,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Ismate y Chilpilla 1a (San Antonio)',86274,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Las Matillas 4a Secc',86274,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Acachapan y Colmena 2da. Sección (La Arena)',86276,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Medellin y Pigua 2a Secc',86276,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Aztlán 1a Sección (Sector La Piedad)',86277,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Corregidora Ortiz 5a Secc',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Pablo L Sidar',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Plátano y Cacao',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Plátano y Cacao 1a Secc',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Plátano y Cacao 2a Secc',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Plátano y Cacao 3a Secc',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(10,4,'Amaton',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Buena Vista Río Nuevo 4a Sección',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Real del Valle',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Pablo L. Sidar (La Aurora)',86283,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'El Amate',86284,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Gaviotas Sur (El Cedral)',86284,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Las Gaviotas Sur 5a Sección (El Monal)',86284,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Residencial Lomas de Parrilla Huapinol',86284,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Santa Cecilia (los Músicos)',86284,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Santa Fe 1 2 y 3ra Sección',86284,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Corozal',86285,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Lázaro Cárdenas 2a Sección',86287,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Playas Del Rosario',86288,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'El Manzano',86289,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'La Agraria',86289,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Villa Unión',86289,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'San Antonio',86289,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Ixtacomitan 5a Sección',86294,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Miraflores 1ra. Sección',86297,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Centro Delegacional 6',86000,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Triangulo Industrial',86010,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(16,4,'Fideicomiso Ciudad Industrial',86010,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'La Pigua',86017,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Insurgentes',86019,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Framboyanes',86020,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Las Golondrinas Priv.',86026,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Real de Minas',86035,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(14,4,'Fovissste 4a Sección Carrizal',86037,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(14,4,'Fovissste 4a Etapa',86038,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Lago Ilusiones',86040,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Lindavista',86050,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Brisas Del Grijalva',86060,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'La Manga III',86068,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Cedros',86068,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Gil y Sáenz (El Águila)',86080,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Guayabal',86090,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Gaviotas Sur Sección San Jose',86090,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Bonampak',86127,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Tamulte de las Barrancas',86150,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Villa las Fuentes',86167,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'La Gloria',86170,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Buena Vista 2da. Sección',86250,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(19,4,'Tercer Milenio',86250,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Aztlán 4a Sección (Chocho y Chilapilla)',86255,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Jolochero 2da. Sección',86270,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Medellín y Madero 1a Secc',86270,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Colinas de Santo Domingo',86270,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Ismate y Chilapilla 2a Sección (Zapotal)',86274,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Chacte',86274,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Las Matillas (San Antonio)',86274,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Pajonal',86275,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Aztlán 3a Sección (Jahuacte)',86278,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Buena Vista Río Nuevo 1ra. Sección',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Corregidora Ortiz 1a Secc',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Gonzalez 2a Secc',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Ixtacomitan 2a Secc',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'J A Sibilla Zurita',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Nuevo Tabasco',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Río Viejo',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Corregidora Ortiz 4a Sección',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(17,4,'Residencial Puerta Real',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Acachapan y Colmena 1a Secc',86281,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Guineo 1a Secc',86283,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Los Gansos',86283,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Huapinol',86284,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Infonavit Parrilla',86284,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Policía y Transito',86284,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Anacleto Canabal 1a Sección',86287,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'La Parrilla 2a Secc La Lima',86288,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Hacienda Del Sol',86288,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'El Encanto',86288,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Santa Rita',86289,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Alvarado Guardacosta',86291,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Boquerón 3a Sección (Guanal)',86294,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Miraflores 2a Secc',86297,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Alvarado Santa Irene 1a Sección',86298,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'La Huasteca 2a Secc',86298,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(15,4,'Secretaria de Hacienda y Crédito Publico',86007,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Interés Social 1',86016,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(14,4,'Indeco Unidad',86017,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Jardines Del Sol',86017,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Vicente Guerrero',86019,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Francisco Villa',86019,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(16,4,'Ciudad Induistrial 2da Etapa',86019,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Valle Marino',86026,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Golondrinas',86027,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'La Hacienda',86035,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Periodista',86059,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Centro Delegacional 5',86073,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Centro Delegacional 2',86077,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Municipal',86090,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Gaviotas Sur Sector Armenia',86099,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(17,4,'Residencial Villas del Sol',86100,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Flores Del Trópico',86105,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Virginia',86108,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Carlos A Madrazo',86126,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Miguel Hidalgo 2a Sección',86127,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(17,4,'Rio Viejo',86127,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Cotip',86129,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(14,4,'Infonavit 3a Secc',86139,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Palma Real',86143,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(17,4,'Paso Real',86143,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Punta Brava',86150,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Popular Pedro C Colorado',86153,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Lomas Del Dorado',86153,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Ixtacomitan 3a Sección',86153,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Real Del Porvenir',86153,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Real de Sabina',86153,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Pino Suárez',86168,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Pensiones',86169,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Militar',86170,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Residencial Esmeralda',86190,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(7,4,'Macultepec',86250,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(7,4,'Tamulte de las Sabanas Real',86250,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'La Ceiba',86250,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Estancia 2a Sección',86253,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(10,4,'Chilapa Margen Izquierda 1a Sección',86254,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Buena Vista 1a Sección',86254,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(10,4,'El Manguito',86257,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Las Rosas',86270,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Medellín y Madero 3a Secc',86270,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Sabanas Nuevas',86274,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Chiquiguao 2da. Sección (Chiquiguaíto)',86274,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Barrancas y Guanal 2a Sección (González)',86276,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'El Zapotal',86276,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Lagartera 2a Secc',86276,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Aztlán 1a Secc',86277,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(10,4,'Jornaleros y Aparceros Del Maluco',86277,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Majagual Matillas',86277,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Gonzalez 1a Secc',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'La Parrilla 1a Secc',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Las Lomas',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Hacienda Casa Blanca',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Hacienda Casa Blanca II',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Los Pinos',86281,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'González 4a Secc',86283,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Río Tinto 3a Secc',86283,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Villa Parrilla',86284,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'San Manuel',86284,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Anacleto Canabal 2a Sección',86287,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Lázaro Cárdenas 2a (21 de Marzo)',86287,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Las Raíces',86289,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Villa el Cielo',86290,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(10,4,'Estanzuela 2a Sección',86293,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Torno Largo 3a Secc',86293,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Plutarco Elías Calles (La Majahua)',86294,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Boquerón 5a Sección (La Lagartera)',86295,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Tepate Abajo (San Isidro)',86295,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Gaviotas Sur (El Chiflón)',86296,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Granja Dorantes',86296,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Barranca y Amate 2a Sección',86297,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Miraflores 2a Secc (Zapotillo)',86297,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Las Margaritas',86016,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Cosmos II',86017,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Las Torres',86026,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Bonanza',86030,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Nance',86030,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Galaxia/tabasco 2000',86035,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Multiochenta',86035,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Villas Del Campestre',86035,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Real de Tabasco',86035,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'El Cedro',86038,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Loma Bonita',86050,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Álvaro Obregón',86050,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Casa Blanca 1a Sección',86060,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(20,4,'Fovissste Casa Blanca',86060,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'La Manga II',86068,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'La Manga I',86069,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Los Tulipanes',86097,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Mayito',86098,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Triunfo La Manga 3',86099,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Jose Colomo',86100,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(19,4,'Alcatraz',86100,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'El Espejo 1',86108,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Carrizal',86108,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'La Joya',86109,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Jose Pages Llergo',86125,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Real Hidalgo',86126,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Lomas de Bella Vista',86126,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Rio Viejo 1a Sección',86127,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'La Ceiba',86127,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(14,4,'Palmitas',86130,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(14,4,'Infonavit 2da Secc',86139,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Privada La Mandarina',86143,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Sanchez Magallanes',86160,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Plutarco Elias Calles Cura Hueso',86170,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Santa Isabel',86250,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Estancia 1a Sección',86253,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Acachapan y Colmena 5a Sección',86255,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(10,4,'La Arena',86257,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Tierra Amarilla 3ra Sección',86270,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'La Ceiba',86270,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Chiquiguao 1ra. Sección',86274,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'La Manga 2a Secc',86275,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(4,4,'Acachapan y Colmena 2a (El Maluco)',86276,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Acachapan y Colmena 4a Secc',86277,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Anona y Tintillo 2a Secc',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Corregidora Ortiz 3a Secc',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Luis Gil Perez',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(10,4,'Carlos A Madrazo',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Platano y Cacao 4a Sección',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Chichicaste',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Medellin y Pigua 1a Secc',86281,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Samarkanda',86281,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'San Ángel',86281,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Estancia Vieja 1a Secc',86283,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Buena Vista Río Nuevo 3a Sección',86283,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Río Tinto 2a Secc',86283,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Villa Floresta',86284,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'El Paraíso',86284,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Jardines de Huapinol',86284,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Casa del Árbol',86284,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Logístico Industrial Tabasco',86287,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Espinoza Galindo',86288,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Constitución',86289,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(10,4,'El Recreo',86289,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'San Vicente',86289,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Gracias México',86289,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Bicentenario',86290,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Plutarco Elias Calles 3a (La Providencia)',86294,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Coronel Traconis (Guerrero 3ra. Sección)',86296,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Coronel Traconis 4a (San Francisco)',86296,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Barranca y Guanal Sección (Tintillo)',86297,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Hueso de Puerco',86298,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Portal Del Agua',86000,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Ciudad Industrial III',86015,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'San José',86019,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Lagunas de San José',86019,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(15,4,'Universidad Autónoma de Tabasco',86025,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Los Caracoles',86029,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Prados de Villahermosa',86030,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Bosques de Villahermosa',86030,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(17,4,'Villa de los Ríos',86035,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'El Country',86039,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(17,4,'Residencial las Puertas',86039,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(19,4,'Paseo las Palmas',86050,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Nueva Villahermosa',86070,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Las Brisas',86095,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'El Parque',86096,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Triunfo la Manga I',86099,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Brisa del Usumacinta',86100,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Tucanes las Quintas',86107,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(19,4,'Los Álamos',86108,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Real Del Usumacinta',86108,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Nueva Invitab',86126,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Buena Vista',86126,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Villa de los Arcos',86130,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(19,4,'Revolución I y II',86140,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Los Huerta Ixtacomitan',86143,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Ixtacomitan 4a Sección',86144,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Ixtacomitan 2a Sección',86144,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Santa Karla II',86150,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Real Del Angel',86153,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'América',86153,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Del Bosque',86160,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Real Del Sur',86170,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Blancas Mariposas',86170,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Loma Real',86170,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Guadalupe',86180,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Palmeira',86190,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(15,4,'Centro Sct Tabasco',86191,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Parrilla 2a Sección Guapinol',86195,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Tocoal',86250,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Estancia',86253,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Estancia 3a Sección',86253,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'La Loma',86253,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Miramar',86254,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Rovirosa',86255,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Buena Vista 3a Sección (Boca de Escoba)',86255,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(10,4,'El Espino',86257,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Lagartera',86271,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Acachapan y Colmena 3a Secc',86277,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Hacienda Esmeralda',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Buena Vista Río Nuevo 2a Sección',86283,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Torno Largo 1a Secc',86284,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Campestre Parrilla',86284,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Chilam Balam',86284,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Monte Líbano Km. 10.5',86284,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Juchimán',86284,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Izmate y Chilapilla 1a Secc',86285,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'La Lima',86288,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Revolución',86289,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(10,4,'El Censo',86289,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(4,4,'La Victoria',86290,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Las Margaritas',86293,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Pablo L Sidar',86294,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Coronel Traconis 5a (San Rafael y San Diego)',86296,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Barrancas y Amate 3a Secc',86297,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Barranca y Guanal Sección (López Portillo)',86297,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Villahermosa Centro',86000,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'El Porvenir 1a Sección',86016,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Las Garzas',86017,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Villa de las Flores',86019,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Privada de Lagunas del Maurel',86019,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(15,4,'Comisión Federal de Electricidad',86030,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Oropeza',86030,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(17,4,'Flamingos',86030,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(14,4,'Nueva Imagen',86030,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(15,4,'Palacio Municipal',86034,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'La Choca',86037,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Adolfo Lopez Mateos',86040,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Florida',86040,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Jesús Garcia',86040,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(14,4,'Fovissste 3a Etapa',86058,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Casa Blanca 2a Sección',86060,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Gaviotas Norte',86068,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(19,4,'Arboledas',86079,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Gaviotas Norte Sector Explanada',86090,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(14,4,'Triunfo La Manga 2',86099,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Miguel Hidalgo 1a Secc',86103,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Aurora',86107,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Villas Del Bosque',86109,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Benito Juárez',86126,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Rio Viejo 2a Sección',86127,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Jardines de Buenavista',86127,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Las Delicias',86140,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Invitab',86143,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Nueva Pensiones',86149,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Jardines Del Sur I y II',86150,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(2,4,'Sabina',86153,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Real de San Jorge',86153,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Parrilla 4a Sección los Acosta',86194,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Encrucijada',86250,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(10,4,'Aniceto',86250,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Medellin y Madero 2a Secc',86270,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Paso Real de La Victoria',86270,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Carlos Pellicer',86270,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Medellín y Madero 4ta. Sección',86270,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Carlos Pellicer Camara 2da Etapa',86270,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Chilapilla 2a Secc',86274,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Las Matillas',86274,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Ismate y Chilapilla 2a Sección (Jahuactillo)',86274,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'La Cruz del Bajío',86275,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Lagartera 1a Secc',86276,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(10,4,'Aztlán 2da. Sección el Cuy',86278,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Medellin y Pigua 3a Secc',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Ángeles Ixtacomitan',86280,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Estancia Vieja 2a Secc',86283,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(10,4,'Santa Catalina',86287,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Las Mercedes',86288,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Topacio',86288,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Ribera de las Raíces',86289,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(12,4,'Monteceibas',86289,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(4,4,'Parrilla 5a Secc',86293,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Boquerón (San Pedro)',86294,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Boquerón 4a Sección (Laguna Nueva)',86294,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Coronel Traconis 1ra Sección (La Isla)',86296,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'Miraflores 3a Secc',86297,1)
INSERT INTO asentamientos(tipo_asentamiento_id,municipio_id,nombre,cp,activo) VALUES(1,4,'La Huasteca 1a Secc',86298,1)

--DELETE FROM asentamientos

--DBCC CHECKIDENT('asentamientos',RESEED,0)

select * from asentamientos where cp = 86140

select * from tipos_asentamientos

select * from municipios

select * from estados

SELECT GETDATE()

select * from proveedores

SELECT d.id, (p.nombre + ' '+ p.ap_paterno + ' ' + p.ap_materno) AS nombre_completo ,d.persona_id, a.nombre AS asentamiento,d.asentamiento_id, tv.nombre AS tipo_vivienda,d.tipo_vivienda_id, d.calle, d.numero_interior, 
d.numero_exterior, d.descripcion, d.fecha_registro, d.fecha_modificacion, d.activo 
FROM dbo.domicilios AS d
INNER JOIN personas AS p ON p.id = d.persona_id
INNER JOIN asentamientos AS a ON a.id = d.asentamiento_id
INNER JOIN tipos_viviendas AS tv ON tv.id = d.tipo_vivienda_id


SELECT * FROM tipos_viviendas

INSERT INTO tipos_viviendas VALUES(1,'Material',1)
INSERT INTO tipos_viviendas VALUES(2,'Lamina',1)
INSERT INTO tipos_viviendas VALUES(3,'Madera',1)
INSERT INTO tipos_viviendas VALUES(4,'Otros',1)

delete from domicilios
delete from medios_comunicacion
delete from clientes
delete from empleados
delete from personas

select * from PERSONAS
select * from EMPLEADOS
select * from clientes


SELECT p.id, tp.nombre AS tipo_producto, p.tipo_producto_id, p.nombre, 
p.descripcion, p.precio_costo, p.precio_contado, p.precio_credito, p.precio_enganche,p.precio_pago_semanal,
p.stock_minimo, p.stock_maximo,p.activo 
FROM dbo.productos AS p
INNER JOIN dbo.tipos_productos AS tp
ON tp.id = p.tipo_producto_id



select * from productos

delete from productos
